Smulchman/historical-media

controllers/api/index.js
controllers/homeRoutes.js
controllers/index.js

This pull request contains the route paths needed to route to the homepage and the api routes. The requests also contains the template routes for the homepage and the user profile

Write authorization middleware

---

views/layouts/main.handlebars

❗ Please **DO NOT** open a Pull Request without creating an Issue first. Failure to do so will result in the rejection of the pull request.
Fixes #[issue]
Please provide a detailed explanation of the PR. What existing problem does it solve?
Please provide an overview of code changes, especially key files and areas of significant change.
path/to/file
- views/layouts/main.handlebars
- change
- change
Demonstrate that the pull request is functional. For example: the exact commands to be run and their output; screenshots if the PR modifies the UI.
Self-explanatory.

add mainHTML

---

controllers/homeRoutes.js
controllers/index.js
db/schema.sql
views/layouts/main.handlebars

this pull requests, gets the project in a ready state for testing our handlebars.

8 get the project ready for basic testing

---

views/layouts/main.handlebars

add bootstrap link

---

.env.example
db/schema.sql

Adds db name to env.example and adds "USE history_db" to schema.sql

adds db name to env.example and adds USE functionality to the schema.sql

---

models/blog.js
models/event.js
models/user.js
server.js

Purpose 
To fix the event model issue

fixes event.js to database json and fixes the naming of the models

---

models/event.js
package.json
server.js
utils/scheduler.js

- Scheduler has been added with an api request to be executed at midnight.
- "Wikipedia" column on the event table has been changed so that it accepts nulls 
- New fetch package 'node-fetch' has been added

18 implement a scheduler

---

package.json
views/homepage.handlebars
views/layouts/main.handlebars

fixed handlebars

---

controllers/homeRoutes.js

To create login and sign up routes

Create login and sign-up routes

---

controllers/homeRoutes.js
models/event.js
server.js
utils/scheduler.js

- Even model now stores day and month
- Scheduler now works dynamically with the current day 
- The get route will generate 10 random events from the current day and send that list to the handlebar

made the scheduler dynamic to current day, changed the event model

---

controllers/homeRoutes.js
views/blog.handlebars
views/homepage.handlebars
views/layouts/main.handlebars
views/partials/partial.handlebars

Homepage now populates year and event description!

38 style homepage

---

controllers/api/blogRoutes.js
controllers/api/index.js
controllers/api/userRoutes.js
controllers/homeRoutes.js

created blog routes 
Post route for blogs - requires user to be logged in 
Get route for dashboard - will return all the blogs related to the currently logged in user 
Get route for rec blogs - returns 5 most recent blogs 
Added the query to return 5 most recent blogs to the homepage route
Sessions Now hold the user_id key value

44 post route for blog

---

controllers/homeRoutes.js
public/js/login.js
views/layouts/main.handlebars
views/login.handlebars
views/signup.handlebars

the login form is now working, sign up is currently unfunctional

30 create button listener for login and sign up

---

public/js/signup.js
views/signup.handlebars

fixed sign up forum

---

controllers/homeRoutes.js
views/event.handlebars

all events page connected

---

public/css/style.css
views/event.handlebars
views/extrainfo.handlebars
views/homepage.handlebars
views/layouts/main.handlebars

fixed history media logo. Its now centered and colored background runs the full width of screen

Centered logo

---

controllers/api/blogRoutes.js
controllers/homeRoutes.js
public/css/style.css
public/js/loginButton.js
public/js/logout.js
public/js/universalButtons.js
views/layouts/main.handlebars
views/partials/parti-dash.handlebars
views/partials/recentblogpartial.handlebars
views/userDash.handlebars

- homepage handlebar now has access to user and event  info for the most recent blogs 
- dashboard now has access to user info and the event info for the given blogs 
- Dashboard handlebar has been altered so that if no blogs are available it will display a message
- Fixed some unnecessarily repeated code

92 dashboard get user info

---

controllers/homeRoutes.js
public/js/blogData.js
public/js/login.js
public/js/post.js
public/js/signup.js
utils/helpers.js
views/404.handlebars
views/extrainfo.handlebars
views/layouts/main.handlebars
views/partials/eventpartial.handlebars
views/partials/homepartial.handlebars
views/partials/recentblogpartial.handlebars
views/signup.handlebars

'View more links' is now functional 
event route is set up 
some code rework

99 back end features

---

public/css/style.css
views/extrainfo.handlebars
views/partials/eventpartial.handlebars
views/partials/extrainfopartial.handlebars
views/partials/homepartial.handlebars
views/partials/parti-dash.handlebars
views/partials/recentblogpartial.handlebars
views/partials/wikipartials.handlebars

Lots of small changes. Changed headers in dashboard, made events slightly bigger, changed links in more info to green, and more .

116 fix blogs on more info page

---

views/blog.handlebars

Added event title to write a blog post page.

added event title to blog post page

---

controllers/homeRoutes.js
package.json
public/css/style.css
public/js/blogData.js
public/js/eventDetails.js
public/js/helpers.js
public/js/login.js
public/js/popup.js
public/js/post.js
public/js/signup.js
utils/helpers.js
views/blog.handlebars
views/extrainfo.handlebars
views/layouts/main.handlebars
views/login.handlebars
views/partials/recentblogpartial.handlebars
views/partials/wikipartials.handlebars
views/signup.handlebars

- Single event page now has a 'blog about this event' button that is functional 
- Single event page will display 'No Blogs Published" If no blogs were written for it 
- Most recent blogs will have the event be clickable, it will redirect to the single event page for that event 
- Post a blog page now has a clickable event that will send the user to the event's page for that event
- Some styling fixes such as,  the main logo animation is fixed 
- Helper function for the html script files is created and all repeating functions have been deleted 
- Some alert statements were deleted, animations were used to signal to the user that the action could not be performed

121 polishing things
